
[mechanics]
	#Base duration for any food in ticks (Default: 2400 = 2 minutes)
	#Range: > 0
	baseTimeTicks = 2400
	#Ticks added per point of Nutrition (Default: 600)
	#Range: > 0
	nutritionMultiplier = 700
	#Ticks added per point of Saturation * Nutrition (Default: 1200)
	#Range: > 0
	saturationMultiplier = 1400
	#Health multiplier per point of Nutrition (Default: 0.5 = 1 HP per 2 Nutrition)
	#Range: 0.0 ~ 10.0
	healthMultiplier = 0.5
	#The absolute tick threshold where the hunger bar starts visually dropping. (Default: 37200 = 31 minutes)
	#Range: > 1
	hungerThresholdTicks = 37200
	#How many ticks of food duration are lost when 1 hunger point is externally drained (e.g. Vein Mining). (Default: 300)
	#Range: > 0
	externalDrainPenalty = 300

[healing]
	#Healing module mode.
	#VANILLA: Heals naturally over time when food level is high.
	#PARTIAL: Heals exactly the extra max HP granted by eating new foods slowly over time.
	#NONE: No natural healing.
	#Allowed Values: VANILLA, PARTIAL, NONE
	healingMode = "PARTIAL"
	#If VANILLA mode is selected, how many ticks between each 1 HP heal? (Default: 80)
	#Range: > 1
	vanillaHealingRate = 80
	#Minimum hunger level required to heal in VANILLA mode (Default: 18)
	#Range: 0 ~ 20
	vanillaHealingHungerThreshold = 18
	#If VANILLA mode is selected, how much exhaustion to apply per 1 HP healed? (Default: 6.0)
	#Range: 0.0 ~ 40.0
	vanillaHealingExhaustion = 6.0
	#If PARTIAL mode is selected, how many ticks between each 1 HP heal for the bonus HP? (Default: 20 = 1 second)
	#Range: > 1
	partialHealingRate = 20

