
["Config for Sam's Combat Indicators"]
	#Should damage numbers show DEFAULT: true
	enable_damage_numbers = true
	#Damage number duration (in ticks) DEFAULT: 30
	number_duration = 30
	#Duration damage numbers flash a different color initially (set to 0 to disable) (in ticks) DEFAULT: 10
	initial_hit_time = 10
	#Start damage number color red value (0-255) DEFAULT: 255
	start_number_color_r = 255
	#Start damage number color green value (0-255) DEFAULT: 102
	start_number_color_g = 102
	#Start damage number color blue value (0-255) DEFAULT: 0
	start_number_color_b = 0
	#End damage number color red value (0-255) DEFAULT: 255
	end_number_color_r = 255
	#End damage number color green (0-255) DEFAULT: 255
	end_number_color_g = 255
	#End damage number color blue value (0-255) DEFAULT: 0
	end_number_color_b = 0
	#Should damage that kills be a different color DEFAULT: true
	separate_kill_color = true
	#Kill damage number color red value (0-255) DEFAULT: 255
	kill_number_color_r = 255
	#Kill damage number color green (0-255) DEFAULT: 0
	kill_number_color_g = 0
	#Kill damage number color blue value (0-255) DEFAULT: 0
	kill_number_color_b = 0
	#Number base scale DEFAULT: 3.0
	number_base_scale = 3.0
	#Scale increase per successive hit (only applies when stacking numbers is on) DEFAULT: 1.0
	number_increment_scale = 1.0
	#How fast numbers decrease in scale (unit per second) (DEFAULT: 1.5)
	number_decrement_speed = 1.5
	#Should damage numbers on a target sum up?
	stack_damage_numbers = true
	#Should damage numbers spray in a random direction?
	spray_damage_numbers = false
	#Initial spray velocity of numbers (in pixels per second) DEFAULT: 150.0
	spray_velocity = 150.0
	#How fast numbers slow down (Loss in % of velocity per second e.g. 0.27 = 27% velocity lost per second) DEFAULT: 0.27
	number_friction = 0.27
	#How fast numbers accelerate down (pixels/s^2) DEFAULT: 0.0
	number_gravity = 0.0
	#Range from -angle to +angle that numbers will spray (in degrees) DEFAULT: 180.0
	spray_angle_range = 180.0
	#Range angle offset applied to all numbers (in degrees) DEFAULT: 0.0
	spray_angle_offset = 0.0
	#Range in degrees (-rotate_range to +rotate_range) between which damage numbers will randomly rotate (set to zero to disable)
	rotate_range = 15
	#Should damage taken indicators show DEFAULT: true
	enable_damage_taken_indicator = true
	#How long damage taken indicator lasts (in ticks) DEFAULT: 60
	damage_taken_indicator_duration = 60
	#How long damage taken is big on initial hit (in ticks) DEFAULT: 20
	damage_taken_indicator_big_duration = 20
	#Base scale size for damage taken indicator (DEFAULT : 1.0)
	damage_taken_indicator_min_size_scale = 1.0
	#Maximum scale size multiplier for damage taken indicator (DEFAULT : 2.0)
	damage_taken_indicator_max_size_scale = 2.0
	#Damage taken indicator base distance from center of screen (in pixels) (DEFAULT : 220)
	damage_taken_indicator_distance = 220
	#Biggest hit (damage that deals 100% max health) color red value (0-255) DEFAULT: 255
	big_hit_indicator_color_r = 255
	#Biggest hit (damage that deals 100% max health) color green value (0-255) DEFAULT: 0
	big_hit_indicator_color_g = 0
	#Biggest hit (damage that deals 100% max health) color blue value (0-255) DEFAULT: 0
	big_hit_indicator_color_b = 0
	#Smallest hit (damage that deals 0% max health) color red value (0-255) DEFAULT: 255
	small_hit_indicator_color_r = 255
	#Smallest hit (damage that deals 0% max health) color green value (0-255) DEFAULT: 242
	small_hit_indicator_color_g = 242
	#Smallest hit (damage that deals 0% max health) color blue value (0-255) DEFAULT: 0
	small_hit_indicator_color_b = 0

